Runs shellcheck and Rubocop on everything
Manually fixed because autofix doesn't exist yet.

https://github.com/koalaman/shellcheck/issues/1220

diff --git a/scripts/vagrant-scp b/scripts/vagrant-scp
--- a/scripts/vagrant-scp
+++ b/scripts/vagrant-scp
@@ -1,6 +1,6 @@
 #!/bin/sh
-OPTIONS=`vagrant ssh-config | awk -v ORS=' ' '{print "-o " $1 "=" $2}'`
-if [ ${VDEBUG} ]; then
+OPTIONS=$(vagrant ssh-config | awk -v ORS=' ' '{print "-o " $1 "=" $2}')
+if [ "${VDEBUG}" ]; then
   echo "${OPTIONS}" "$@"
 fi
-scp ${OPTIONS} "$@" || echo "Transfer failed. Did you use 'default:' as the target?"
+scp "${OPTIONS}" "$@" || echo "Transfer failed. Did you use 'default:' as the target?"
